#!/bin/sh /etc/rc.common
# vtunnel init script
# Copyright (C) 2018 Carnegie Mellon University
 
START=92
STOP=93

NAME=vtunnel
PROG=/bin/vtunnel

USE_PROCD=1

start_service() {	
	procd_open_instance
	procd_set_param command "$PROG" -s
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param pidfile /var/run/vtunnel.pid
	procd_close_instance
}		 
 
